name: sarf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.2
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  http: ^1.3.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - lang/
  - assets/
  - assets/fonts/
  - assets/fonts/ar/
  - assets/fonts/en/
  - assets/icons/
  - assets/images/
  - assets/lottie/
  - .env

fonts:
  - family: AR
    fonts:
      - asset: sarf/assets/fonts/ar/IBMPlexSans-Bold.ttf
      - asset: sarf/assets/fonts/ar/IBMPlexSans-Bold.ttf
        weight: 700
  
  - family: EN
    fonts:
      - asset: assets/fonts/en/Share-Regular.ttf
      - asset: assets/fonts/en/Share-Bold.ttf
        weight: 700
