FROM python:latest

WORKDIR /sarf

COPY . .

ENV DB_HOST="{localhost}"
ENV DB_PORT="{5432}"
ENV DB_NAME="{my_database}"
ENV DB_USER="{root}"
ENV DB_PASS="{secret_password}"
ENV DB_URL="{url of database to be used in migration"
ENV DB_ENGINE="{url of database to be used in connect with database"
ENV ENV="{development/testing/production}"

EXPOSE 3000


RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]